services:
  tfg_ganache_final:
    image: trufflesuite/ganache-cli:latest
    container_name: tfg_ganache_final
    restart: always
    command: ["--db=/app/database", "--mnemonic=tfg_blockchain_secret_seed_phrase", "--networkId=1778279372631", "--host=0.0.0.0"]
    volumes:
      - ./ganache_data:/app/database
    networks:
      - tfg_internal_nw
    ports:
      - "8545:8545"

  tfg_backend_final:
    image: node:18-alpine
    container_name: tfg_backend_final
    restart: always
    working_dir: /app/blockchain
    volumes:
      - .:/app
    depends_on:
      - tfg_ganache_final
    networks:
      - tfg_internal_nw
    command: sh -c "npm install && node server.js"

  tfg_frontend_final:
    image: nginx:stable-alpine
    container_name: tfg_frontend_final
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - tfg_internal_nw

  tfg_cloudflare_tunnel_api:
    image: cloudflare/cloudflared:latest
    container_name: tfg_cloudflare_tunnel_api
    restart: always
    command: tunnel --url http://tfg_backend_final:3000
    networks:
      - tfg_internal_nw

  tfg_cloudflare_tunnel_web:
    image: cloudflare/cloudflared:latest
    container_name: tfg_cloudflare_tunnel_web
    restart: always
    command: tunnel --url http://tfg_frontend_final:80
    networks:
      - tfg_internal_nw

  tfg_cloudflare_tunnel_grafana:
    image: cloudflare/cloudflared:latest
    container_name: tfg_cloudflare_tunnel_grafana
    restart: always
    command: tunnel --url http://tfg_grafana:3000
    networks:
      - tfg_internal_nw

  tfg_prometheus:
    image: prom/prometheus
    container_name: tfg_prometheus
    restart: always
    volumes:
      - ./prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tfg_internal_nw

  tfg_grafana:
    image: grafana/grafana
    container_name: tfg_grafana
    restart: always
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - tfg_internal_nw

networks:
  tfg_internal_nw:
    driver: bridge
