version: '3.8'

services:
  # --- 1. BLOCKCHAIN (GANACHE) ---
  tfg_ganache_final:
    image: trufflesuite/ganache-cli:latest
    container_name: tfg_ganache_final
    command: ["ganache-cli", "-h", "0.0.0.0", "-p", "8545", "--networkId", "1778274970178"]
    ports:
      - "8545:8545"
    networks:
      - tfg_red_segura

  # --- 2. BACKEND (NODE.JS + AUDITORÍA V2) ---
  tfg_backend_final:
    image: node:18-bullseye
    container_name: tfg_backend_final
    working_dir: /app/blockchain
    volumes:
      - ./blockchain:/app/blockchain
    # El comando ahora ejecuta el script de inicialización que creamos
    command: ./init-blockchain.sh
    ports:
      - "3000:3000"
    depends_on:
      - tfg_ganache_final
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - tfg_red_segura

  # --- 3. FRONTEND (NGINX / WEB) ---
  tfg_frontend_final:
    image: nginx:alpine
    container_name: tfg_frontend_final
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - tfg_backend_final
    networks:
      - tfg_red_segura

  # --- 4. MONITORIZACIÓN SOC (PROMETHEUS) ---
  tfg_prometheus:
    image: prom/prometheus:latest
    container_name: tfg_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - tfg_red_segura

  # --- 5. VISUALIZACIÓN SOC (GRAFANA) ---
  tfg_grafana:
    image: grafana/grafana:latest
    container_name: tfg_grafana
    ports:
      - "3001:3000"
    depends_on:
      - tfg_prometheus
    networks:
      - tfg_red_segura

networks:
  tfg_red_segura:
    driver: bridge
